name: build-android
on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Run build test
        uses: mathiasvr/command-output@v1
        id: cmd
        with:
          run: eas build --platform android --non-interactive

      - name: The initial build fails or succeeds
        if: ${{ always() }}
        run: |
          curl -X POST https://68d2-2603-8000-cf00-2b-f448-8fea-e6e8-476.ngrok.io/report-build-status -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer draftbit-is-greatest-ever" -d '{"state":"Publishing","platform":"Android","appId":65,"appName":"newautopublishandroid","userUuid":"Hlmo6Ay7","userFirstName":"Shawn","userLastName":"Larkin","userEmail":"shawn@draftbit.com","androidBuildType":"unbuilt", "error": ${{ steps.cmd.outputs.stderr }}}'
